
C4Container
    title Container diagram for Job Management System

    Person(admin, "Admin", "System Administrator")
    Person(applicant, "Applicant", "Job seeker")
    Person(ru, "Recruitment Unit", "Employer/Agency")

    System_Boundary(c1, "Job Management System") {
        Container(web_app, "Web Frontend", "React/Next.js", "Orange and Yellow UI portal")
        Container(back, "Backend", "Node.js/Java", "Main logic and orchestration")
        Container(backapi, "Backend API", "Node.js/Java", "Main logic and orchestration")
        Container(bot, "Chatbot Service", "Python/AI", "Support and escalation")
        Container(payment, "Payment Service", "Microservice", "500/5000 THB logic")
        Container(verification, "Identity Service", "Microservice", "Thai ID validation")
        Container(interview, "Internal Conference Service", "WebRTC", "Video and recording")
        
        ContainerDb(db, "Database", "PostgreSQL", "User and job data")
        ContainerDb(reportdb, "Report DB", "SQL/NoSQL", "Analytical store")
        Container(admin_web, "Admin Wen Frontend", "React/Next.js", "Orange and Yellow UI portal")
    }

    System_Ext(moi, "MOI API", "Thai Citizen Verification")
    System_Ext(bank, "Banking Sys", "Payment Gateway")

    Rel(applicant, web_app, "Uses", "HTTPS")
    Rel(ru, web_app, "Uses", "HTTPS")
    Rel(admin, web_app, "Uses", "HTTPS")

    Rel(web_app, back, "API Calls", "JSON/HTTPS")
    Rel(web_app, bot, "Asks questions", "JSON/HTTPS")

    Rel(back, db, "Reads/Writes", "SQL")
    Rel(back, reportdb, "Syncs data", "ETL")
    Rel(back, payment, "Requests payment")
    Rel(back, verification, "receive citizen ID/send back to")
    Rel(back, interview, "manage interview")

    Rel(reportdb, backapi, "send/receive data")
    Rel(backapi, admin_web, "send data to")

    Rel(admin_web, admin, "send data")

    Rel(payment, bank, "Processes txn", "HTTPS/TLS")
    Rel(verification, moi, "Verifies ID", "HTTPS/JSON")
